Repository for-men/ForTickets, pull requests merged in 2024-10, with the labels that each got.

#19 Feat/8 auth user
  .gitignore
  application/gateway-service/build.gradle
  application/gateway-service/src/main/java/com/fortickets/gatewayservice/CustomPostFilter.java
  application/gateway-service/src/main/java/com/fortickets/gatewayservice/CustomPreFilter.java
  application/gateway-service/src/main/java/com/fortickets/gatewayservice/JwtAuthenticationFilter.java
  application/gateway-service/src/main/resources/application.yml
  application/user-service/build.gradle
  application/user-service/src/main/java/com/fortickets/userservice/UserServiceApplication.java
  application/user-service/src/main/java/com/fortickets/userservice/application/dto/requset/LoginReq.java
  application/user-service/src/main/java/com/fortickets/userservice/application/dto/requset/SignUpReq.java
  application/user-service/src/main/java/com/fortickets/userservice/application/dto/requset/UpdateUserReq.java
  application/user-service/src/main/java/com/fortickets/userservice/application/dto/response/GetUserRes.java
  application/user-service/src/main/java/com/fortickets/userservice/application/mapper/UserMapper.java
  application/user-service/src/main/java/com/fortickets/userservice/application/security/JwtAuthorizationFilter.java
  application/user-service/src/main/java/com/fortickets/userservice/application/security/JwtUtil.java
  application/user-service/src/main/java/com/fortickets/userservice/application/security/SecurityConfig.java
  application/user-service/src/main/java/com/fortickets/userservice/application/security/UserDetailsImpl.java
  application/user-service/src/main/java/com/fortickets/userservice/application/security/UserDetailsServiceImpl.java
  application/user-service/src/main/java/com/fortickets/userservice/application/service/AuthService.java
  application/user-service/src/main/java/com/fortickets/userservice/application/service/UserService.java
  application/user-service/src/main/java/com/fortickets/userservice/domain/entity/User.java
  application/user-service/src/main/java/com/fortickets/userservice/domain/entity/UserRoleEnum.java
  application/user-service/src/main/java/com/fortickets/userservice/domain/repository/UserRepository.java
  application/user-service/src/main/java/com/fortickets/userservice/presentation/controller/AuthController.java
  application/user-service/src/main/java/com/fortickets/userservice/presentation/controller/UserController.java
  application/user-service/src/main/resources/application.yml
  application/user-service/src/main/resources/user-data.sql
  component/common/src/main/java/com/fortickets/common/ErrorCase.java
Labels: feat

#20 [#18] feat(concert) : concert , stage, Schedule 엔티티 추가및 연관관계 설정
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/Concert.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/Schedule.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/Stage.java
Labels: feat

#23 예매 API 구현
  application/order-service/src/main/java/com/fortickets/orderservice/application/client/ConcertClient.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/res/GetConcertDetailRes.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/res/GetConcertRes.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/response/CreateBookingRes.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/response/GetBookingRes.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/response/GetScheduleRes.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/service/BookingService.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/entity/Booking.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/mapper/BookingMapper.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/repository/BookingRepository.java
  application/order-service/src/main/java/com/fortickets/orderservice/presentation/controller/BookingController.java
  component/common/src/main/java/com/fortickets/common/BookingStatus.java
  component/common/src/main/java/com/fortickets/common/ErrorCase.java
Labels: feat

#22 콘서트 등록 , 콘서트 리스트 조회 기능 구현
  application/concert-service/src/main/java/com/fortickets/concertservice/application/dto/request/CreateConcertReq.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/dto/response/CreateConcertRes.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/dto/response/GetConcertRes.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/service/ConcertService.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/entity/Concert.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/entity/Schedule.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/entity/Stage.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/mapper/ConcertMapper.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/repository/ConcertRepository.java
  application/concert-service/src/main/java/com/fortickets/concertservice/presentation/ConcertController.java
  application/concert-service/src/main/resources/application.yml
Labels: feat

#27 [#17] feat(prometheus): 프로메테우스, 그라파나 설정 및 연동
  application/concert-service/src/main/resources/application.yml
  application/eureka/src/main/resources/application.yml
  application/gateway-service/src/main/resources/application.yml
  application/order-service/src/main/resources/application.yml
  application/prometheus-service/build.gradle
  application/prometheus-service/src/main/java/com/fortickets/prometheusservice/PrometheusServiceApplication.java
  application/prometheus-service/src/main/resources/application.yml
  application/prometheus-service/src/main/resources/docker-compose.yml
  application/prometheus-service/src/main/resources/prometheus.yml
  application/user-service/src/main/java/com/fortickets/userservice/application/security/SecurityConfig.java
  application/user-service/src/main/resources/application.yml
  build.gradle
  settings.gradle
Labels: feat

#28 공연장 생성 및 조회
  application/concert-service/src/main/java/com/fortickets/concertservice/application/dto/CreateStageRes.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/dto/request/CreateStageReq.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/dto/response/GetConcertRes.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/dto/response/GetStageRes.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/service/StageService.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/entity/Stage.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/mapper/ConcertMapper.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/mapper/StageMapper.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/repository/ConcertRepository.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/repository/StageRepository.java
  application/concert-service/src/main/java/com/fortickets/concertservice/presentation/StageController.java
  component/common/src/main/java/com/fortickets/common/ErrorCase.java
Labels: feat

#30 Feat/#24 payment feature
  application/order-service/src/main/java/com/fortickets/orderservice/application/client/ConcertClient.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/request/ConfirmBookingReq.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/request/CreateBookingReq.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/request/CreatePaymentReq.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/response/GetConcertDetailRes.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/response/GetConcertRes.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/response/GetPaymentDetailRes.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/response/GetPaymentRes.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/response/GetUserRes.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/service/BookingService.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/service/PaymentService.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/entity/Booking.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/entity/Payment.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/mapper/BookingMapper.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/mapper/PaymentMapper.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/repository/BookingRepository.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/repository/PaymentRepository.java
  application/order-service/src/main/java/com/fortickets/orderservice/presentation/controller/BookingController.java
  application/order-service/src/main/java/com/fortickets/orderservice/presentation/controller/PaymentController.java
  application/order-service/src/main/resources/application.yml
  component/common/src/main/java/com/fortickets/common/ErrorCase.java
  component/common/src/main/java/com/fortickets/common/PaymentStatus.java
Labels: feat

#33 [#29] feat(gatling): gatling 부하 테스트 세팅
  .DS_Store
  application/prometheus-service/src/main/resources/prometheus.yml
  application/user-service/src/main/java/com/fortickets/userservice/presentation/controller/AuthController.java
  gatling/.gatling/example.package.conf
  gatling/.gatling/package.conf
  gatling/.github/dependabot.yml
  gatling/.gitignore
  gatling/README.md
  gatling/build.gradle
  gatling/gradle/wrapper/gradle-wrapper.jar
  gatling/gradle/wrapper/gradle-wrapper.properties
  gatling/gradlew
  gatling/gradlew.bat
  gatling/settings.gradle
  gatling/src/gatling/java/computerdatabase/ComputerDatabaseSimulation.java
  gatling/src/gatling/java/computerdatabase/UserSimulation.java
  gatling/src/gatling/resources/gatling.conf
  gatling/src/gatling/resources/logback-test.xml
  gatling/src/gatling/resources/search.csv
  settings.gradle
Labels: feat

#36 Feat/8 auth user
  application/gateway-service/src/main/java/com/fortickets/gatewayservice/JwtAuthenticationFilter.java
  application/user-service/build.gradle
  application/user-service/docker-compose.yml
  application/user-service/src/main/java/com/fortickets/userservice/application/FeignClientConfig.java
  application/user-service/src/main/java/com/fortickets/userservice/application/OrderClient.java
  application/user-service/src/main/java/com/fortickets/userservice/application/security/JwtAuthenticationFilterForCommon.java
  application/user-service/src/main/java/com/fortickets/userservice/application/security/JwtAuthenticationFilterForUserService.java
  application/user-service/src/main/java/com/fortickets/userservice/application/security/SecurityConfig.java
  application/user-service/src/main/java/com/fortickets/userservice/application/service/UserService.java
  application/user-service/src/main/resources/application.yml
  component/security/build.gradle
  component/security/src/main/java/com/fortickets/security/JwtAuthenticationFilterForCommon.java
  component/security/src/main/java/com/fortickets/security/SecurityConfig.java
  docker-compose.yml
Labels: fix

#39 Feat/#34 feignclient api
  application/concert-service/build.gradle
  application/concert-service/src/main/java/com/fortickets/concertservice/application/dto/response/GetConcertDetailRes.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/dto/response/GetScheduleDetailRes.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/service/ConcertService.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/service/ScheduleService.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/mapper/ConcertMapper.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/mapper/ScheduleMapper.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/repository/ConcertRepository.java
  application/concert-service/src/main/java/com/fortickets/concertservice/infrastructure/config/ComponentConfig.java
  application/concert-service/src/main/java/com/fortickets/concertservice/presentation/ConcertController.java
  application/concert-service/src/main/java/com/fortickets/concertservice/presentation/ScheduleController.java
  application/order-service/build.gradle
  application/order-service/src/main/java/com/fortickets/orderservice/application/client/ConcertClient.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/response/GetConcertRes.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/response/GetScheduleDetailRes.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/service/BookingService.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/entity/Booking.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/entity/Payment.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/mapper/BookingMapper.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/mapper/PaymentMapper.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/repository/BookingRepository.java
  application/order-service/src/main/java/com/fortickets/orderservice/infrastructure/config/ComponentConfig.java
  application/order-service/src/main/java/com/fortickets/orderservice/presentation/controller/BookingController.java
  application/order-service/src/main/resources/application.yml
  application/user-service/src/main/java/com/fortickets/userservice/application/service/UserService.java
  application/user-service/src/main/java/com/fortickets/userservice/domain/repository/UserRepository.java
  application/user-service/src/main/java/com/fortickets/userservice/presentation/controller/UserController.java
  component/exception/src/main/java/com/fortickets/exception/GlobalExceptionHandler.java
  component/security/build.gradle
  component/security/src/main/java/com/fortickets/security/JwtAuthenticationFilterForCommon.java
  component/security/src/main/resources/application.yml
Labels: feat

#40 feat: payment 관련 client api 구현
  application/concert-service/src/main/java/com/fortickets/concertservice/application/service/ConcertService.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/mapper/ConcertMapper.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/repository/ConcertRepository.java
  application/concert-service/src/main/java/com/fortickets/concertservice/presentation/ConcertController.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/client/ConcertClient.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/service/PaymentService.java
  application/order-service/src/main/java/com/fortickets/orderservice/presentation/controller/PaymentController.java
  component/jpa/src/main/java/com/fortickets/jpa/AuditorAwareImpl.java
Labels: feat

#41 [#35] test(gatling) 테스트 시나리오 작성
  application/concert-service/src/main/resources/concert-data.sql
  application/concert-service/src/main/resources/schedule-data.sql
  application/concert-service/src/main/resources/stage-data.sql
  application/order-service/src/main/resources/booking-data.sql
  application/user-service/src/main/java/com/fortickets/userservice/application/security/JwtAuthenticationFilterForUserService.java
  build.gradle
  component/security/src/main/java/com/fortickets/security/JwtAuthenticationFilterForCommon.java
  gatling/.gitignore
  gatling/build.gradle
  gatling/src/gatling/java/computerdatabase/BookingSimulation1.java
  gatling/src/gatling/java/computerdatabase/BookingSimulation2.java
  gatling/src/gatling/java/computerdatabase/ComputerDatabaseSimulation.java
  gatling/src/gatling/java/computerdatabase/ScheduleSimulation1.java
  gatling/src/gatling/java/computerdatabase/ScheduleSimulation2.java
  gatling/src/gatling/java/computerdatabase/ScheduleSimulation3.java
  gatling/src/gatling/java/computerdatabase/UserSimulation.java
  settings.gradle
Labels: test

#43 fix(config) : 프로메테우스 연동 실패 오류 해결, db 데이터 추가, 프로메테우스 eureka client 제거
  application/order-service/src/main/resources/booking-data.sql
  application/order-service/src/main/resources/payment-data.sql
  build.gradle
  component/security/src/main/java/com/fortickets/security/SecurityConfig.java
Labels: fix

#47 Feat/#44 redis
  .gitignore
  application/concert-service/src/main/resources/application.yml
  application/order-service/src/main/resources/application.yml
  application/prometheus-service/src/main/resources/docker-compose.yml
  application/user-service/build.gradle
  application/user-service/src/main/java/com/fortickets/userservice/application/service/RedisService.java
  application/user-service/src/main/java/com/fortickets/userservice/presentation/controller/RedisConnectionTest.java
  application/user-service/src/main/java/com/fortickets/userservice/presentation/controller/RedisController.java
  application/user-service/src/main/resources/application.yml
  build.gradle
  component/security/src/main/java/com/fortickets/security/JwtAuthenticationFilterForCommon.java
  docker-compose.yml
  local-redis-stack.conf
Labels: feat

#55 [#54] feat(Redis): Redis Cluster 적용
  .gitignore
  build.gradle
  component/redis/build.gradle
  component/redis/src/main/java/com/fortickets/redis/config/RedisConfig.java
  docker-compose.yml
Labels: feat

#56 [#51] feat(Redis): 분산 락 적용 - createBooking
  application/order-service/src/main/java/com/fortickets/orderservice/application/service/BookingService.java
  application/order-service/src/main/java/com/fortickets/orderservice/infrastructure/config/ComponentConfig.java
  component/redis/build.gradle
  component/redis/src/main/java/com/fortickets/redis/config/RedissonConfig.java
  component/redis/src/main/resources/application.yml
  docker-compose.yml
Labels: feat

#57 feat: kafka 적용, 대기열 시스템 적용
  application/gateway-service/build.gradle
  application/gateway-service/src/main/java/com/fortickets/gatewayservice/kafka/KafkaOffsetManager.java
  application/gateway-service/src/main/java/com/fortickets/gatewayservice/kafka/KafkaTicketIssuer.java
  application/gateway-service/src/main/java/com/fortickets/gatewayservice/kafka/TicketFilter.java
  application/gateway-service/src/main/java/com/fortickets/gatewayservice/kafka/TrafficMonitor.java
  application/gateway-service/src/main/resources/application.yml
  application/order-service/build.gradle
  application/order-service/src/main/java/com/fortickets/orderservice/application/service/BookingService.java
  application/order-service/src/main/resources/application.yml
  docker-compose.yml
  gatling/src/gatling/java/computerdatabase/BookingSimulation2.java
  gatling/src/gatling/java/computerdatabase/QueueLoadTest.java
Labels: feat

#66 [#62] feat(QueryDSL): 검색 기능에 QueryDSL 적용
  application/concert-service/src/main/java/com/fortickets/concertservice/application/service/ConcertService.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/repository/ConcertRepository.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/repository/ConcertRepositoryCustom.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/repository/ConcertRepositoryImpl.java
  application/concert-service/src/main/java/com/fortickets/concertservice/infrastructure/config/QuerydslConfig.java
  application/concert-service/src/main/java/com/fortickets/concertservice/presentation/ConcertController.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/service/BookingService.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/repository/BookingRepository.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/repository/BookingRepositoryCustom.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/repository/BookingRepositoryImpl.java
  application/order-service/src/main/java/com/fortickets/orderservice/infrastructure/config/QuerydslConfig.java
  application/order-service/src/main/resources/application.yml
  build.gradle
  docker-compose.yml
Labels: feat

#69 예매, 결제 권한 추가 MANAGER는 요청 가능 설정
  application/order-service/src/main/java/com/fortickets/orderservice/application/service/BookingService.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/service/PaymentService.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/repository/BookingRepository.java
  application/order-service/src/main/java/com/fortickets/orderservice/presentation/controller/BookingController.java
  application/order-service/src/main/java/com/fortickets/orderservice/presentation/controller/PaymentController.java
Labels: feat

#72 Refactor/#70 concert service
  application/concert-service/src/main/java/com/fortickets/concertservice/application/service/ConcertService.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/service/ScheduleService.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/service/StageService.java
  application/concert-service/src/main/java/com/fortickets/concertservice/presentation/ConcertController.java
  application/concert-service/src/main/java/com/fortickets/concertservice/presentation/ScheduleController.java
  application/concert-service/src/main/java/com/fortickets/concertservice/presentation/StageController.java
  application/concert-service/src/main/resources/concert-data.sql
  application/order-service/src/main/resources/application.yml
  application/user-service/src/main/java/com/fortickets/userservice/application/service/AuthService.java
  application/user-service/src/main/java/com/fortickets/userservice/infrastructure/config/ComponentConfig.java
  application/user-service/src/main/resources/application.yml
Labels: refactor

#82 Feat/#81 Order 예매 확정 시 응답 값 추가 & 2차 MVP 코드 리팩토링
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/CreatePaymentRes.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/response/GetBookingRes.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/response/GetConcertDetailRes.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/service/BookingService.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/service/PaymentService.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/mapper/BookingMapper.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/mapper/PaymentMapper.java
  application/order-service/src/main/java/com/fortickets/orderservice/presentation/controller/BookingController.java
  application/order-service/src/main/java/com/fortickets/orderservice/presentation/controller/PaymentController.java
Labels: feat, refactor

#83 Release/mvp2
  application/order-service/src/main/java/com/fortickets/orderservice/application/client/ConcertClient.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/client/UserClient.java
  component/redis/src/main/java/com/fortickets/redis/config/RedissonConfig.java
  docker-compose.yml
  release/image/concert-service-image.dockerfile
  release/image/eureka-image.dockerfile
  release/image/gateway-service-image.dockerfile
  release/image/order-service-image.dockerfile
  release/image/user-service-image.dockerfile
Labels: config

#85 #74 feat(order) : 공연 서비스 Cache 적용
  application/concert-service/src/main/java/com/fortickets/concertservice/application/dto/response/GetConcertRes.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/dto/response/GetConcertsRes.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/service/ConcertService.java
  application/concert-service/src/main/java/com/fortickets/concertservice/infrastructure/config/ComponentConfig.java
  application/concert-service/src/main/java/com/fortickets/concertservice/presentation/ConcertController.java
  application/concert-service/src/main/resources/application.yml
  application/user-service/src/main/resources/user-data.sql
  component/redis/src/main/java/com/fortickets/redis/RestPage.java
  component/redis/src/main/java/com/fortickets/redis/config/CacheConfig.java
Labels: feat

#86 cicd 기능 구현 ( github actions)
  .github/workflows/gradle.yml
  Dockerfile
  docker-compose.yml
  dockerTagAndPush.sh
  release/image/concert-service-image.dockerfile
  release/image/eureka-image.dockerfile
  release/image/gateway-service-image.dockerfile
  release/image/order-service-image.dockerfile
  release/image/user-service-image.dockerfile
Labels: build, ci

#92 Feat/#78 gateway kafka 연동 문제 해결
  application/gateway-service/src/main/java/com/fortickets/gatewayservice/kafka/KafkaConfig.java
  application/gateway-service/src/main/resources/application-local.yml
  application/gateway-service/src/main/resources/application.yml
  application/order-service/src/main/java/com/fortickets/orderservice/infrastructure/messaging/KafkaProducer.java
  application/order-service/src/main/java/com/fortickets/orderservice/infrastructure/scheduler/OrderScheduler.java
  application/order-service/src/main/resources/application-local.yml
  application/order-service/src/main/resources/payment-data.sql
  docker-compose-local.yml
  gatling/src/gatling/java/computerdatabase/BookingCancelSimulation.java
  gatling/src/gatling/java/computerdatabase/ConcertListSimulation.java
Labels: feat, build

#93 #87 docs(ReadMe) : 리드미 작성
  README.md
Labels: docs

#99 Concert validation 설정, 운영 서버 Redis 연결 안되는 문제 해결
  .github/workflows/gradle.yml
  application/concert-service/src/main/java/com/fortickets/concertservice/application/dto/request/CreateConcertReq.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/dto/request/CreateStageReq.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/dto/request/UpdateConcertReq.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/dto/request/UpdateStageReq.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/service/ConcertService.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/service/ScheduleService.java
  application/concert-service/src/main/java/com/fortickets/concertservice/presentation/ConcertController.java
  application/concert-service/src/main/java/com/fortickets/concertservice/presentation/ScheduleController.java
  application/concert-service/src/main/java/com/fortickets/concertservice/presentation/StageController.java
  application/concert-service/src/main/resources/application.yml
Labels: refactor, fix
