Repository for-men/ForTickets, pull requests merged in 2024-09, with the labels that each got.

#5 #4 jpa, exception, common 모듈 생성. order 초기 세팅
  .gitignore
  application/concert-service/build.gradle
  application/gateway-service/build.gradle
  application/gateway-service/src/main/resources/application.yml
  application/order-service/build.gradle
  application/order-service/docker-compose.yml
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/request/CreateBookingReq.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/response/CreateBookingRes.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/service/BookingService.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/entity/Booking.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/entity/BookingStatus.java
  application/order-service/src/main/java/com/fortickets/orderservice/domain/repository/BookingRepository.java
  application/order-service/src/main/java/com/fortickets/orderservice/infrastructure/client/UserClient.java
  application/order-service/src/main/java/com/fortickets/orderservice/presentation/controller/BookingController.java
  application/order-service/src/main/resources/application.yml
  application/user-service/build.gradle
  build.gradle
  component/common/build.gradle
  component/common/src/main/java/com/fortickets/common/CommonResponse.java
  component/common/src/main/java/com/fortickets/common/ErrorCase.java
  component/exception/build.gradle
  component/exception/src/main/java/com/fortickets/exception/GlobalException.java
  component/exception/src/main/java/com/fortickets/exception/GlobalExceptionHandler.java
  component/exception/src/main/java/com/fortickets/exception/InvalidInputMapper.java
  component/exception/src/main/java/com/fortickets/exception/InvalidInputRes.java
  component/jpa/build.gradle
  component/jpa/src/main/java/com/fortickets/jpa/AuditorAwareImpl.java
  component/jpa/src/main/java/com/fortickets/jpa/BaseEntity.java
  component/jpa/src/main/java/com/fortickets/jpa/JpaAuditingConfig.java
  settings.gradle
Labels: enhancement

#13 feat: 각 서비스 docker compose 설정 db 자동 생성
  application/concert-service/build.gradle
  application/concert-service/docker-compose.yml
  application/concert-service/src/main/resources/application.yml
  application/eureka/build.gradle
  application/eureka/src/main/java/com/fortickets/eureka/EurekaApplication.java
  application/eureka/src/main/resources/application.yml
  application/gateway-service/src/main/resources/application.yml
  application/order-service/src/main/java/com/fortickets/orderservice/application/client/UserClient.java
  application/order-service/src/main/java/com/fortickets/orderservice/infrastructure/client/UserClient.java
  application/order-service/src/main/resources/application.yml
  application/user-service/build.gradle
  application/user-service/docker-compose.yml
  application/user-service/src/main/resources/application.yml
  build.gradle
  settings.gradle
Labels: documentation

#12 유레카 서버 모듈 생성, 게이트웨이 서비스 라우팅 설정
  application/concert-service/build.gradle
  application/concert-service/docker-compose.yml
  application/concert-service/src/main/resources/application.yml
  application/eureka/build.gradle
  application/eureka/src/main/java/com/fortickets/eureka/EurekaApplication.java
  application/eureka/src/main/resources/application.yml
  application/gateway-service/src/main/resources/application.yml
  application/order-service/src/main/java/com/fortickets/orderservice/application/client/UserClient.java
  application/order-service/src/main/java/com/fortickets/orderservice/infrastructure/client/UserClient.java
  application/order-service/src/main/resources/application.yml
  application/user-service/build.gradle
  application/user-service/docker-compose.yml
  application/user-service/src/main/resources/application.yml
  build.gradle
  settings.gradle
Labels: enhancement

#16 [#15] chore : 테스트용 객체 SQL문 작성
  application/concert-service/src/main/resources/concert-data.sql
  application/concert-service/src/main/resources/schedule-data.sql
  application/concert-service/src/main/resources/stage-data.sql
  application/order-service/src/main/resources/booking-data.sql
  application/order-service/src/main/resources/payment-data.sql
  application/user-service/src/main/resources/user-data.sql
Labels: chore
