Repository for-men/ForTickets, pull requests merged in 2024-11, with the labels that each got.

#106 Perf/#105 조회 성능 최적화, 리팩토링
  application/concert-service/src/main/java/com/fortickets/concertservice/application/dto/response/GetConcertDetailRes.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/service/ConcertService.java
  application/concert-service/src/main/java/com/fortickets/concertservice/application/service/ScheduleService.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/mapper/ConcertMapper.java
  application/concert-service/src/main/java/com/fortickets/concertservice/domain/repository/ConcertRepository.java
  application/concert-service/src/main/java/com/fortickets/concertservice/presentation/ConcertController.java
  application/concert-service/src/main/resources/application.yml
  application/gateway-service/src/main/resources/application.yml
  application/order-service/src/main/java/com/fortickets/orderservice/application/client/ConcertClient.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/service/BookingService.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/service/PaymentService.java
  application/order-service/src/main/java/com/fortickets/orderservice/infrastructure/scheduler/OrderScheduler.java
  application/order-service/src/main/resources/application.yml
  docker-compose.yml
Labels: refactor, perf

#107 Feat/#103 order pg payment
  .gitignore
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/request/RequestPaymentReq.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/response/CreatePaymentRes.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/service/PaymentService.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/service/TossPaymentsService.java
  application/order-service/src/main/java/com/fortickets/orderservice/infrastructure/config/AppConfig.java
  application/order-service/src/main/resources/application.yml
  application/order-service/src/main/resources/widget/checkout.html
  application/order-service/src/main/resources/widget/fail.html
  application/order-service/src/main/resources/widget/success.html
  component/common/src/main/java/com/fortickets/common/util/ErrorCase.java
Labels: feat

#109 #108 feat(payment) : 토스 결제창 연동 (보안 관련 문제 해결)
  application/gateway-service/src/main/java/com/fortickets/gatewayservice/JwtAuthenticationFilter.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/request/RequestPaymentReq.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/service/PaymentService.java
  application/order-service/src/main/resources/static/widget/checkout.html
  application/order-service/src/main/resources/static/widget/confirm.html
  application/order-service/src/main/resources/static/widget/fail.html
  application/order-service/src/main/resources/static/widget/success.html
  component/common/src/main/java/com/fortickets/common/security/CustomPreFilter.java
  component/common/src/main/java/com/fortickets/common/security/SecurityConfig.java
Labels: feat

#113 Fix/#112 kafka queue
  application/gateway-service/build.gradle
  application/gateway-service/src/main/java/com/fortickets/gatewayservice/kafka/KafakaViewController.java
  application/gateway-service/src/main/java/com/fortickets/gatewayservice/kafka/KafkaConsumerManager.java
  application/gateway-service/src/main/java/com/fortickets/gatewayservice/kafka/KafkaFilter.java
  application/gateway-service/src/main/java/com/fortickets/gatewayservice/kafka/KafkaMonitor.java
  application/gateway-service/src/main/java/com/fortickets/gatewayservice/kafka/KafkaMonitorController.java
  application/gateway-service/src/main/java/com/fortickets/gatewayservice/kafka/KafkaProducerManager.java
  application/gateway-service/src/main/resources/application-local.yml
  application/gateway-service/src/main/resources/application.yml
  application/gateway-service/src/main/resources/static/index.html
  application/order-service/src/main/resources/application.yml
  docker-compose-local.yml
  docker-compose.yml
  gatling/src/gatling/java/computerdatabase/BookingSimulation2.java
  gatling/src/gatling/java/computerdatabase/ConcertSimulation.java
  gatling/src/gatling/java/computerdatabase/ScheduleSimulation3.java
  gatling/src/gatling/java/computerdatabase/UserSignUpSimulation.java
Labels: fix

#114 Feat/#103 order pg payment v2
  application/gateway-service/src/main/java/com/fortickets/gatewayservice/kafka/KafkaViewController.java
  application/order-service/build.gradle
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/request/CreatePaymentReq.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/dto/request/RequestPaymentReq.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/service/PaymentService.java
  application/order-service/src/main/java/com/fortickets/orderservice/application/service/TossPaymentsService.java
  application/order-service/src/main/resources/static/widget/checkout.html
  application/order-service/src/main/resources/static/widget/confirm.html
  application/order-service/src/main/resources/static/widget/css/style.css
  application/order-service/src/main/resources/static/widget/fail.html
  application/order-service/src/main/resources/static/widget/success.html
Labels: feat

#116 [#115] test(concert): 공연 서비스 테스트코드 작성
  application/concert-service/src/test/java/com/fortickets/concertservice/application/service/ConcertServiceTest.java
Labels: test
